all: output-sync/packer-sync output-async/packer-async output-postgresql/packer-postgresql

output-ubuntu/packer-ubuntu: ubuntu.json
	packer build ubuntu.json

output-sync/packer-sync: app.json sync/* output-ubuntu/packer-ubuntu
	packer build -var "service=sync" app.json

output-async/packer-async: app.json async/* output-ubuntu/packer-ubuntu
	packer build -var "service=async" app.json

output-postgresql/packer-postgresql: postgres.json output-ubuntu/packer-ubuntu
	packer build postgres.json

sync: output-sync/packer-sync
	qemu-system-x86_64 \
        -machine type=pc,accel=kvm \
        -m 1024M \
        -device virtio-net,netdev=user.0 \
        -netdev user,id=user.0,hostfwd=tcp::8000-:80 \
        -drive file=output-sync/packer-sync,if=virtio,cache=writeback,discard=ignore,format=qcow2 \
        -vnc :0

async: output-async/packer-async
	qemu-system-x86_64 \
        -machine type=pc,accel=kvm \
        -m 1024M \
        -device virtio-net,netdev=user.0 \
        -netdev user,id=user.0,hostfwd=tcp::8000-:80 \
        -drive file=output-async/packer-async,if=virtio,cache=writeback,discard=ignore,format=qcow2 \
        -vnc :0

postgres: output-postgresql/packer-postgresql
	qemu-system-x86_64 \
        -machine type=pc,accel=kvm \
        -m 1024M \
        -device virtio-net,netdev=user.0 \
        -netdev user,id=user.0,hostfwd=tcp::5678-:5432 \
        -drive file=output-postgresql/packer-postgresql,if=virtio,cache=writeback,discard=ignore,format=qcow2 \
        -vnc :1
cc
